services:
    pgdb:
      container_name: pgdb
      image: postgres
      environment:
        POSTGRES_PASSWORD: 5432
        POSTGRES_HOST: 'host.docker.internal'
        POSTGRES_DB: 'counting_the_bill_system'
      extra_hosts:
        - "host.docker.internal:host-gateway"
      ports:
        - "3306:3306"
      volumes:
        - ./pgdb:/docker-entrypoint-initdb.d

    application:
      container_name: boozooka/counting_the_bill_system
        build: .
        expose:
          - "8080"
        ports:
          - "8080:8080"
        environment:
          WAIT_HOSTS: mysql:5432
        depends_on:
          - mysql

